import { Inter } from 'next/font/google'
import StoreProvider from '@/components/StoreProvider'
const inter = Inter({ subsets: ['latin'] })
import Header from '@/components/Header'
import Footer from '/components/Footer'
import './css/layout.css'
import './css/normalize.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <StoreProvider>
          <Header/>
            <main>
              {children}
            </main>
          <Footer />  
      </StoreProvider>
      </body>
    </html>
  )
}
